# Generated by Django 3.1.4 on 2020-12-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=255)),
                ('mdesc', models.CharField(max_length=255)),
                ('mimg', models.CharField(max_length=255)),
            ],
        ),
    ]
